### ISSUE TITLE
Provide a /cid/multihash endpoint

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-explorer#2]
I think it might be an idea to provide a /tx/<tx_hash> /cid/ endpoint in chlu-explorer, where it can load a review matching that transaction or multihash.

See https://github.com/ChluNetwork/chlu-demo/issues/47#issuecomment-366413104

**Comment by fazo96** [comment]
Related: https://github.com/ChluNetwork/chlu-explorer/issues/3 this PR adds a field so that arbitrary RR can be loaded
